## This configuration installs vscode and configures it.

- shell:
    - yay -S --needed --noconfirm visual-studio-code-insiders-bin
    - code-insiders --install-extension ms-azuretools.vscode-docker
    - code-insiders --install-extension ms-python.debugpy
    - code-insiders --install-extension ms-python.python
    - code-insiders --install-extension ms-python.vscode-pylance
    - code-insiders --install-extension ms-vscode.cpptools
    - code-insiders --install-extension Catppuccin.catppuccin-vsc
