## This configuration installs vscode and configures it.

- shell:
    - yay -S --needed --noconfirm code code-marketplace
    - code --install-extension ms-azuretools.vscode-docker
    - code --install-extension ms-python.debugpy
    - code --install-extension ms-python.python
    - code --install-extension ms-python.vscode-pylance
    - code --install-extension ms-vscode.cpptools
    - code --install-extension Catppuccin.catppuccin-vsc
