## This configuration installs vesktop (discord wannabe) with the appropriate themes and plugins.

- shell:
    - yay -S --needed --noconfirm vesktop-bin
    
- link:
    ~/.config/vesktop/themes: dots/home/user/.config/vesktop/themes
    ~/.config/vesktop/settings: dots/home/user/.config/vesktop/settings
    ~/.config/vesktop/settings.json: dots/home/user/.config/vesktop/settings.json
