# This configuration installs extensions for firefox

- shell:
    - yay -S --needed --noconfirm firefox

- sudo:
    - link:
        /etc/firefox/policies/policies.json: dots/etc/firefox/policies/policies.json
