# Installs an autologin greeter
- shell:
    - yay -S --needed --noconfirm lightdm lightdm-gtk-greeter

- sudo:
    - shell:
        - groupadd -r autologin || true
        - gpasswd -a ${SUDO_USER:-$USER} autologin || true
    - link:
        /etc/lightdm/lightdm.conf: dots/etc/lightdm/lightdm.conf
    - shell:
        - grep -q '^autologin-user=' /etc/lightdm/lightdm.conf || echo "autologin-user=${SUDO_USER:-$USER}" >> /etc/lightdm/lightdm.conf
        - systemctl enable --now lightdm.service