## This configuration installs sway and the system-wide theme spread across multiple files ;(

- shell:
    - >
      yay -S --needed --noconfirm
      acpi
      arandr
      arc-gtk-theme-eos
      archlinux-xdg-menu
      awesome-terminal-fonts
      dex
      dmenu
      dunst
      eos-settings-i3wm
      endeavouros-xfce4-terminal-colors
      eos-lightdm-slick-theme
      eos-qogir-icons
      feh
      i3-wm
      i3blocks
      i3lock
      i3status
      jq
      nwg-look
      network-manager-applet
      numlockx
      playerctl
      polkit-gnome
      rofi
      scrot
      sysstat
      xbindkeys
      xdg-user-dirs-gtk
      xfce4-terminal
      xorg-server
      xorg-apps
      xterm
      power-profile-daemon
      networkmanager

- link:
    ~/.config/autostart: dots/home/user/.config/autostart
    ~/.config/dunst: dots/home/user/.config/dunst
    ~/.config/gtk-3.0: dots/home/user/.config/gtk-3.0
    ~/.config/gtk-4.0: dots/home/user/.config/gtk-4.0
    ~/.config/i3: dots/home/user/.config/i3
    ~/.config/nano: dots/home/user/.config/nano
    ~/.config/nwg-look: dots/home/user/.config/nwg-look
    ~/.config/rofi: dots/home/user/.config/rofi
    ~/.config/xsettingsd: dots/home/user/.config/xsettingsd
    ~/.config/wallpaper.png: dots/home/user/.config/wallpaper.png

    ~/.local/share/nwg-look: dots/home/user/.local/share/nwg-look
    ~/.local/share/rofi: dots/home/user/.local/share/rofi

    ~/.profile: dots/home/user/.profile
    ~/.gtkrc-2.0: dots/home/user/.gtkrc-2.0
    ~/.Xresources: dots/home/user/.Xresources

- sudo:
    - link:
        /etc/locale.gen: dots/etc/locale.gen
    - shell:
        - systemctl enable bluetooth.service
        - systemctl enable NetworkManager.service
        - chmod +x /home/$SUDO_USER/.config/i3/scripts/*
        - locale-gen
