- shell:
    - >
      yay -S --needed --noconfirm
      flatpak
      dbeaver
      qbittorrent
    - flatpak install --noninteractive flathub org.videolan.VLC
    - flatpak install --noninteractive flathub net.werwolv.ImHex
    - flatpak install --noninteractive flathub com.getpostman.Postman