## This configuration installs spotify with the appropriate themes and plugins.

- shell:
    - yay -S --needed --noconfirm spotify spicetify-cli

- link:
    ~/.config/spicetify: dots/.config/spicetify

- sudo:
    - shell:
        - chmod a+wr /opt/spotify && chmod a+wr /opt/spotify/Apps -R

#- shell:
#    - spicetify apply
