## This configuration installs sway and the system-wide theme spread across multiple files ;(

- shell:
    - >
      yay -S --needed --noconfirm
      swayfx
      swayidle
      swaylock-effects
      swaybg
      azote
      sworkstyle
      autotiling
      dex
      gtk-engine-murrine
      greetd-tuigreet
      wl-clipboard
      ulauncher
      wofi
      waybar
      acpi
      bluez
      blueman
      network-manager-applet
      wayland-protocols
      xorg-xwayland
      egl-wayland
      gtk-layer-shell
      xdg-desktop-portal-wlr
      polkit-gnome
      brightnessctl
      sysstat
      htop
      mako
      ttf-nerd-fonts-symbols
      ttf-jetbrains-mono
      ttf-ubuntu-font-family
      sway-input-config
      nwg-displays
      grim
      slurp
      jq
      catppuccin-gtk-theme-frappe
      catppuccin-cursors-frappe
      swayosd-git

- link:
    ~/.config/wofi: dots/home/user/.config/wofi
    ~/.config/ulauncher: dots/home/user/.config/ulauncher
    ~/.config/mako: dots/home/user/.config/mako
    ~/.config/swaylock: dots/home/user/.config/swaylock
    ~/.config/sway: dots/home/user/.config/sway
    ~/.config/waybar: dots/home/user/.config/waybar
    ~/.config/gtk-3.0: dots/home/user/.config/gtk-3.0
    ~/.config/sworkstyle: dots/home/user/.config/sworkstyle
    ~/.config/wallpaper.png: dots/home/user/.config/wallpaper.png

    ~/.profile: dots/home/user/.profile
    ~/.gtkrc-2.0: dots/home/user/.gtkrc-2.0
    ~/.azotebg: dots/home/user/.azotebg

- sudo:
    - link:
        /etc/locale.gen: dots/etc/locale.gen
    - shell:
        - systemctl enable greetd.service
        - systemctl enable bluetooth.service
        - systemctl enable --now swayosd-libinput-backend.service
        - locale-gen
