## This configuration adds all the other basic utilities

- shell:
    - >
      yay -S --needed --noconfirm
      thunar
      thunar-media-tags-plugin
      thunar-volman
      thunar-archive-plugin
      file-roller
      gvfs
      tumbler
      foot
      imv
      xed
      ttf-font-awesome

- link:
    ~/.config/Thunar: dots/.config/Thunar
    ~/.config/xfce4: dots/.config/xfce4
    ~/.config/foot: dots/.config/foot
    ~/.local/share/xed: dots/.local/share/xed

- sudo:
    - shell: 
        - dbus-launch dconf load / < dots/dconf 
