## This configuration adds all the other basic utilities

- shell:
    - >
      yay -S --needed --noconfirm
      thunar
      thunar-media-tags-plugin
      thunar-volman
      thunar-archive-plugin
      file-roller
      gvfs
      gvfs-afc
      gvfs-gphoto2
      gvfs-mtp
      gvfs-nfs
      gvfs-smb
      tumbler
      foot
      imv
      xed
      mpv
      unzip
      zip
      xarchiver
      galculator
      ttf-font-awesome
      blueman

- link:
    ~/.config/Thunar: dots/home/user/.config/Thunar
    ~/.config/xfce4: dots/home/user/.config/xfce4
    
    ~/.local/share/xed: dots/home/user/.local/share/xed

- sudo:
    - shell: 
        - dbus-launch dconf load / < dots/dconf 
