## This configuration adds all the other basic utilities

- link:
    ~/.config/Thunar: dots/.config/Thunar
    ~/.config/xfce4: dots/.config/xfce4
    ~/.config/foot: dots/.config/foot
    
    ~/.local/share/xed: dots/.local/share/xed

    ~/.local/share/applications/org.codeberg.dnkl.footclient.desktop: dots/.local/share/applications/org.codeberg.dnkl.footclient.desktop
    ~/.local/share/applications/org.codeberg.dnkl.foot-server.desktop: dots/.local/share/applications/org.codeberg.dnkl.foot-server.desktop
    ~/.local/share/applications/org.gnome.FileRoller.desktop: dots/.local/share/applications/org.gnome.FileRoller.desktop 
    ~/.local/share/applications/thunar-bulk-rename.desktop: dots/.local/share/applications/thunar-bulk-rename.desktop
    ~/.local/share/applications/thunar-settings.desktop: dots/.local/share/applications/thunar-settings.desktop
    ~/.local/share/applications/thunar-volman-settings.desktop: dots/.local/share/applications/thunar-volman-settings.desktop

- shell:
    - >
      yay -S --needed --noconfirm
      thunar
      thunar-media-tags-plugin
      thunar-volman
      thunar-archive-plugin
      file-roller
      gvfs
      tumbler
      foot
      imv
      xed
      c-lolcat
      ttf-font-awesome

- sudo:
    - shell: 
        - dbus-launch dconf load / < dots/dconf 
