fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'xed' = ''
'Spotify' = ''
'/NVIM ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'telegramdesktop' = ''
'Telegram' = ''
'Wfica' = ''
'org.remmina.Remmina' = ''
'SchildiChat' = ''
'Element' = ''
'nheko' = ''
'/Firefox .*Private Browsing/' = ''
'/(?i)Google Drive.*Firefox/' = ''
'/(?i)Google Calendar.*Firefox/' = ''
'/(?i)MAX.*Iridium/' = ''
'/(?i)Dashboards -.*Iridium/' = ''
'/(?i) youtube.*Firefox/' = ''
'// Twitter.*Firefox/' = ''
'/ eBay.*Firefox/' = ''
'/(?i)reddit.*Firefox/' = ''
'/(?i)drive.*Firefox/' = ''
'/(?i)Github.*Firefox/' = ''
'/Google.*Firefox/' = ''
'org.kde.dolphin' = ''
'/home/.*Dolphin/' = ''
'thunar' = { type = 'generic', value = '' }
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'Google-chrome' = ''
'Chromium' = ''
'Chromium-browser' = ''
'org.kde.kcharselect' = ''
'Zim' = ''
'image-roll' = ''
'pavucontrol' = ''
'obs' = ''
'galculator' = '🖩'
'mpv' = '🎞'
'blueberry.py' = '' 
'wdisplays' = '🖵'
'Pinta' = '🖌'
'GParted' = '🖴'
'/GParted/' = '🖴'
'org.inkscape.Inkscape' = '🖋'
'/Application Launcher/' = ''
'vesktop' = ''

